[workspace]

members = [
    "filter",
    "icon",
    "maple_cli",
    "matcher",
    "matcher/extracted_fzy",
    "nerdtree",
    "pattern",
    "printer",
    "source_item",
    "utility",
    "upgrade",
]
